[package]
name = "stecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frunk = "0.4.2"
memoffset = "0.9.0"
thunderdome = "0.6.1"

[profile.release-with-debug]
inherits = "release"
debug = true
